defaults:
  - _self_

base_model: "Llama_3.2-1B"
dataset_size: 100
n_epochs: 10
n_samples: 0
lora: false
kg: false
pii_rate: 0.05
n_gpu: 3
n_cpu: 24  # 8*n_gpu
no_submit: false
# Set base_path to repo root, home_path to your home (for job logs)
base_path: "."
home_path: "~"
backend: "vllm"
infer_only: false
injection_strategy: "manual"
