base_dir: /gpfs/commons/groups/gursoy_lab/fpollet/Git/clinical-exposure-metric
filters:
  dataset_size: 1
  model: 1B
  n_epochs: 2
  pii_rate: 1.0
  pii_types:
  - name-patient
  - name-attending
  prompt: 'Name: '
inputs:
  budget: 10000
  generation_file: /gpfs/commons/groups/gursoy_lab/fpollet/Git/clinical-exposure-metric/outputs/pii_leakage/experimental-recall-all/generation_False_all_{dataset_size}_{model}_{pii_rate}_{n_epochs}_{budget}.csv
  src_ll_file: /gpfs/commons/groups/gursoy_lab/fpollet/Git/clinical-exposure-metric/outputs/pii_leakage/pipeline/ll_all_output_False_{model}_{dataset_size}_batch.csv
  src_ll_file_base: /gpfs/commons/groups/gursoy_lab/fpollet/Git/clinical-exposure-metric/outputs/pii_leakage/pipeline/ll_all_output_True_{model}_{dataset_size}_batch.csv
models:
  base_model_1B: /gpfs/commons/groups/gursoy_lab/fpollet/Git/clinical-exposure-metric/models/base/Llama_3.2-1B
  base_model_8B: /gpfs/commons/groups/gursoy_lab/fpollet/Git/clinical-exposure-metric/models/base/Llama_3.1-8B
output_dir: /gpfs/commons/groups/gursoy_lab/fpollet/Git/clinical-exposure-metric/outputs/pii_leakage/experimental-recall-output/{dataset_size}_{model}_{pii_rate}_{n_epochs}_{budget}
prompts:
- 'Name: '
- 'Patient: '
